# Generated by Django 5.0.6 on 2024-05-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myuser_delete_app_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=255)),
                ('ects', models.IntegerField(max_length=5)),
                ('semester', models.IntegerField(max_length=5)),
                ('elective', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=5)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
            ],
        ),
    ]
