# Generated by Django 5.0.6 on 2024-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='ects',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
