# Generated by Django 5.0.6 on 2024-05-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_subjects_ects_alter_subjects_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Neupisan', 'Neupisan'), ('Upisan', 'Upisan'), ('Polozen', 'Polozen')], default='Neupisan', max_length=10)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subjects')),
            ],
        ),
    ]
