# Generated by Django 5.0.6 on 2024-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_enrollmentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(default='Student', max_length=10),
        ),
    ]
