# Generated by Django 5.0.6 on 2024-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_myuser_username_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentform',
            name='status',
            field=models.CharField(choices=[('Neupisan', 'Neupisan'), ('Upisan', 'Upisan'), ('Polozen', 'Polozen'), ('Izgubio potpis', 'Izgubio potpis')], default='Neupisan', max_length=15),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='elective',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentform',
            unique_together={('student_id', 'subject_id')},
        ),
    ]
